In [ ]:
1)what is numpy? why it is important for data base?
.numpy is python library use for numerical operation.
.It is important for databases because it enables quick data processing and important for handling large datasets efficiently.

In [ ]:
2)differnce between python lists and numpy arrays?
.python lists store multiple type of data
.numpy arrays store only one type of data

In [ ]:
3)how do we create a numpy array of zeros with a specific shape?

In [11]:
import numpy as np
array = np.zeros((3, 4))
print(array)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
4) what are common data types in numpy arrays?
. integer, float, Boolean, string, double

In [ ]:
5)how do you perform perform element-wise addition,substraction,multiplication and division in numpy array?

In [19]:
import numpy as np
array1 = np.array([10, 20, 30])
array2 = np.array([40, 50, 60])
addition = array1 + array2    
subtraction = array1 - array2   
multiplication = array1 * array2    
division = array1 / array2         
print(addition, 
      subtraction,
      multiplication, 
      division)

[50 70 90] [-30 -30 -30] [ 400 1000 1800] [0.25 0.4  0.5 ]


In [ ]:
6)explain concept of array slicing in numpy? 
.Slicing in NumPy is used to extracting range of data from specific portion.

In [25]:
import numpy as np
array = np.array([10, 20, 30, 40, 50])
portion1 = array[1:4]              
print(portion1)

[20 30 40]


In [ ]:
7)how do you find mean, median and mode of a numpy array?
Mean:The average of all numbers in a dataset.
Median:The middle value in dataset
Mode:The most repeated number in a dataset.

In [37]:
import numpy as np
from scipy import stats
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,1])
mean = np.mean(array)
median = np.median(array)
mode = stats.mode(array)
print(mean)
print(median)
print(mode)

4.6
4.5
ModeResult(mode=1, count=2)


In [ ]:
8)what is broad coasting in numpy,and how does it work?
.Broadcasting in NumPy refers to the ability to perform arithmetic operations on arrays of different shapes. 

In [ ]:
9)whatis pandas , what are its key data structures?
.pandas is python libraray 
It's key data structures are
.Series:which is a single column of data
.DataFrame:which is a table with rows and columns. 

In [ ]:
10)how do you import a data from csv file into pandas data frames?
import pandas as pd
import numpy as np
data =pd.read_csv('filename.csv')

In [ ]:
11)how do you select specific rows or a column from data frames?

In [56]:
import pandas as pd
import numpy as np
data ={'Name': ['ossara', 'zuha', 'iqra'],
    'Age': [25, 30, 35],
    'City': ['rawalakot', 'kashmir', 'rawalpindi']}
df = pd.DataFrame(data)
print(df)
rows =df.loc[2]
print(rows)


     Name  Age        City
0  ossara   25   rawalakot
1    zuha   30     kashmir
2    iqra   35  rawalpindi
Name          iqra
Age             35
City    rawalpindi
Name: 2, dtype: object


In [ ]:
12)explain difference between lic and iloc in indexes in pandas?
.loc is used to select rows or column by name. 
.iloc is used to select data by index position.

In [ ]:
13)how do handle missing values (NaN) in dataframes?

In [7]:
import pandas as pd
import numpy as np
data1 ={'emplId': ['e1', 'e2', 'e3'],
    'Age': [25, 30, 35]}
data2 ={'emplId': ['e1', 'e2', 'e3'],
    'salary': [2500, 3000, 3500]}

df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)
print("DataFrame 1:")
print(df1)
print("DataFrame 2:")
print(df2)
pd.concat([df1,df2])


DataFrame 1:
  emplId  Age
0     e1   25
1     e2   30
2     e3   35
DataFrame 2:
  emplId  salary
0     e1    2500
1     e2    3000
2     e3    3500


emplId   Age  salary
0     e1  25.0     NaN
1     e2  30.0     NaN
2     e3  35.0     NaN
0     e1   NaN  2500.0
1     e2   NaN  3000.0
2     e3   NaN  3500.0

14)how do you filter rows in dataframe based on condition?

In [13]:
import pandas as pd
import numpy as np
# Sample DataFrame
data = {'Name': ['ossara', 'zuha', 'iqra'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)
filtered_df = df[df['Age'] > 30]

print(filtered_df)


   Name  Age
2  iqra   35


In [ ]:
15)how do you group data in data frame and perform aggregation?

In [15]:
import pandas as pd
import numpy as np
# Sample DataFrame
data = {'Category': ['A', 'B', 'A', 'B'],
        'Values': [10, 20, 30, 40]}
df = pd.DataFrame(data)
grouped = df.groupby('Category')['Values'].sum()

print(grouped)


Category
A    40
B    60
Name: Values, dtype: int64


In [ ]:
16)what is difference between concat and merge in pandas?
.concat: it is used to combine data without matcing rows and columns.
.merge:it require common column or key to combine data.

In [ ]:
17)You have two DataFrames with some overlapping columns. Describe how 
you would perform an outer join and explain the significance of an outer join 
compared to an inner join.


In [17]:
import pandas as pdiqra
import numpy as np
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['ossara', 'zuha', '']})
df2 = pd.DataFrame({'ID': [3, 4, 5], 'Age': [15, 20, 25]})
result = pd.merge(df1, df2, on='ID', how='outer')
print(result)


   ID    Name   Age
0   1  ossara   NaN
1   2    zuha   NaN
2   3          15.0
3   4     NaN  20.0
4   5     NaN  25.0


In [ ]:
significance:
outer join: it combine all rows from both data frames and adding NaN where there’s no match.
Inner Join: only keeps match rows in both DataFrames. It focus on common data.

In [ ]:
18) Explain the concept of vectorization in NumPy. How does it improve the performance of numerical computations.
.Vectorization in NumPy means performing operations on whole arrays instead of individual elements.
#How It Improves Performance:
Speed: NumPy is faster.
Simplicity: It makes code shorter and easier by handling entire arrays without writing loops.


In [23]:
import pandas as pd
import numpy as np
arr=np.array([1, 2, 3, 4])
result=arr * 4
print(result)


[ 4  8 12 16]


In [ ]:
19)You have a DataFrame with a column containing dates. How would you: (a) Convert the date column to a datetime object? 
(b) Extract the year, month,and day from the dates? (c) Filter the DataFrame to select data from a specific date range?

In [31]:
import pandas as pd
import numpy as np
data = {'Date': ['2023-01-01', '2023-02-15', '2023-03-20']}
df = pd.DataFrame(data)
df['Date'] = pd.to_datetime(df['Date'])
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day
start_date='2023-02-01'
end_date='2024-03-31'
filtered_df = df[(df['Date'] >= start_date) & (df['Date'] <= end_date)]
print("Original DataFrame:")
print(df)
print("\nFiltered DataFrame (dates between 2024-02-01 and 2024-03-31):")
print(filtered_df)


Original DataFrame:
        Date  Year  Month  Day
0 2023-01-01  2023      1    1
1 2023-02-15  2023      2   15
2 2023-03-20  2023      3   20

Filtered DataFrame (dates between 2024-02-01 and 2024-03-31):
        Date  Year  Month  Day
1 2023-02-15  2023      2   15
2 2023-03-20  2023      3   20


In [ ]:
20)Describe a scenario where you would use a GroupBy operation in Pandas,and explain how you would perform an aggregation 
(e.g., calculate the average) within each group.

In [33]:
import pandas as pd
import numpy as np
data = {'Region': ['North', 'South', 'North', 'East', 'South', 'East'],
'Sales': [200, 300, 250, 400, 350, 450]}
df = pd.DataFrame(data)
average_sales = df.groupby('Region')['Sales'].mean()
print("Average Sales per Region:")
print(average_sales)


Average Sales per Region:
Region
East     425.0
North    225.0
South    325.0
Name: Sales, dtype: float64
